---
language: python
services: docker

env:
  global:
    - ROLE_NAME: secure-docker
  matrix:
    - MOLECULE_DISTRO: debian9

install:
  # Install dependencies.
  - pip install -r requirements.txt && pip install -r test-requirements.txt

script:
  # Run tests.
  - molecule test
