---
language: python
services: docker

env:
  matrix:
    - MOLECULE_DISTRO: debian:9
    - MOLECULE_DISTRO: debian:10

install:
  # Install dependencies.
  - pip install -r requirements.txt && pip install -r test-requirements.txt

script:
  # Run tests.
  - molecule test
