---
language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
services:
  - docker

env:
  matrix:
    - MOLECULE_DISTRO: debian:9

before_install: ".bin/setup_travis.sh"

install:
  # Install dependencies.
  - pip install -r requirements.txt && pip install -r test-requirements.txt

script:
  # Run tests.
  - molecule test
